name: Python Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r python-tools/requirements.txt
          pip install -r python-tools/requirements-dev.txt
      - name: Run tests
        run: |
          source .venv/bin/activate
          python -m pytest -q python-tools/tests --junitxml=python-tools/test-report.xml

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: python-test-report
          path: python-tools/test-report.xml

      - name: Publish test report annotations
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: python-tests
          path: python-tools/test-report.xml
          reporter: junit
          fail-on-error: false
